@extends('templates.base')

@section('content-body')
 		<div class="entry-content">
 		
			<div class=""><div class=""><div class="col-xs-12 col-sm-4 pull-right col-md-5 d-social-share-wrap"><div class="col-xs-2 col-xs-offset-5 d-social-share-txt"><span class="d-share-count">35</span><div class="d-share-txt">Shares</div></div><div class="col-xs-5 d-social-share-btns"> <a id="fb_share"> <span class="d-share-btn d-kshitij-iconfacebook"></span></a> <a id="twitter_share"> <span class="d-share-btn d-share-btn-tw d-kshitij-icontwitter"></span></a><a id="linkedin_share"> <span class="d-share-btn icon-linkedin-klinkedin"></span></a></div></div><h3 class="d-section-hero-heading">COLOUR OF MONEY</h3><p class="text-muted d-oneliner">Saturday, May 13, 2017</p><div class="d-section-hero"><div class="row"><div class="col-md-6"><div class="featured" style="background: url(http://colourofmoney.kshitij.com/wp-content/uploads/2017/05/eurusd-quarterly-candles.jpg) center no-repeat;"></div><a href="http://colourofmoney.kshitij.com/long-term-forecasts-euro-yen/"><h3>Long-term forecasts on Euro, Yen and Aussie</h3></a>
                                    <p class="text-muted">Need reliable Euro, Yen and Aussie forecasts for business costing and planning your hedges?
We had started to offer long-term forecasts on Euro, Yen and Aussie, spanning over period of 3-quarters....</p>
                                    <div class="media">
                                        <a class="pull-left" href="#">
                                            <img class="media-object d-avatar" src="http://colourofmoney.kshitij.com/wp-content/uploads/2014/10/about.png">
                                        </a>
                                            <div class="media-body d-author-wrap"><b>Vikram Murarka</b><span class="d-aut-socl-btn"><a target="_blank" href="https://twitter.com/VikramMurarka"><span class="d-kshitij-icontwitter icons"></span></a> <a href="http://in.linkedin.com/in/vikrammurarka" target="_blank"><span class="d-kshitij-iconlinkedin2 icons"></span></a></span></div></div></div><div class="col-md-6"><ul class=""><li class=""><a href=http://colourofmoney.kshitij.com/global-equities-time-breather/><h4>Global Equities: Time for a breather?</h4></a><p class="text-muted">Dow 20453 / World 1843/ BRIC 270 / Nifty 9150...</p></li><li class=""><a href=http://colourofmoney.kshitij.com/got-kshitij-com-advantage/><h4>Have you got the Kshitij.com Advantage?</h4></a><p class="text-muted">Highlights of Kshitij Forecasts: 2016
Kshitij has been making long term...</p></li><li class=""><a href=http://colourofmoney.kshitij.com/study-us-treasury-yields/><h4>Study on US Treasury Yields</h4></a><p class="text-muted">EXECUTIVE SUMMARY:  
Our last reading was for chances of slow...</p></li><li class=""><a href=http://colourofmoney.kshitij.com/stop-press-kshitij-com-reliable/><h4>Stop Press! Or, why KSHITIJ.COM is reliable</h4></a><p class="text-muted">Merriam Webster defines “Quality assurance” as “a program for the...</p></li><li class=""><a href=http://colourofmoney.kshitij.com/can-us-election-different-history/><h4>Can this US election be different from history</h4></a><p class="text-muted">02-Nov-16 / DJIA 17960
EXECUTIVE SUMMARY:
The US stock market generally remains...</p></li></ul></div></div></div></div></div><div class="d-section-list-text-only"><a href=http://colourofmoney.kshitij.com/category/risk-management><h2 class="linkhover">Risk Management</h2></a><div class="d-section-list-text-only-wrap"><div class="col-md-12"><div class="row"><div class="col-md-1 viewers"><h4>902</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/how-much-are-you-really-paying/"><h4>How Much Did You Really PAY/ RECEIVE?</h4></a><div class="text-muted">
The old financial year is over. The accounts are done and profit/ loss has been...</div></div></div><hr><div class="row"><div class="col-md-1 viewers"><h4>642</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/how-to-use-a-forecast/"><h4>FORECASTS: LOVE THEM? HATE THEM? USE THEM.</h4></a><div class="text-muted">Forecasts and Accountability
Everybody loves a forecast and wants to know where Dollar-Rupee is headed. This...</div></div></div><hr><div class="row"><div class="col-md-1 viewers"><h4>2.49k</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/sumproduct-for-calculating-weighted-average/"><h4>Excel Tip 2 - Use SUMPRODUCT for Weighted Average</h4></a><div class="text-muted">Here's another very important MS Excel tip, one that I got from one of our...</div></div></div></div><div class="clearfix"></div></div></div><div class="d-section-list-text-only"><a href=http://colourofmoney.kshitij.com/category/investment-psychology><h2 class="linkhover">Investment Psychology</h2></a><div class="d-section-list-text-only-wrap"><div class="col-md-12"><div class="row"><div class="col-md-1 viewers"><h4>848</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/kshitij-com-forecast-currencies/"><h4>Why does kshitij.com forecast currencies?</h4></a><div class="text-muted">A friend sent an interesting inspirational YouTube video link the other day. The speaker in...</div></div></div><hr><div class="row"><div class="col-md-1 viewers"><h4>823</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/short-term-or-long-term-investment/"><h4>Investing - Where do we want to be right - Short Term or Long Term?</h4></a><div class="text-muted">We invest to make profits, to multiply our money. Should we invest for the long...</div></div></div><hr><div class="row"><div class="col-md-1 viewers"><h4>725</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/com100909/"><h4>FX is a Commodity, not an asset</h4></a><div class="text-muted">
Does not have the features of an asset
FX is not an asset because it hasn't...</div></div></div></div><div class="clearfix"></div></div></div><div class="d-section-list-text-only"><a href=http://colourofmoney.kshitij.com/category/research><h2 class="linkhover">Research</h2></a><div class="d-section-list-text-only-wrap"><div class="col-md-12"><div class="row"><div class="col-md-1 viewers"><h4>8.02k</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/long-term-forecasts-euro-yen/"><h4>Long-term forecasts on Euro, Yen and Aussie</h4></a><div class="text-muted">Need reliable Euro, Yen and Aussie forecasts for business costing and planning your hedges?
We had...</div></div></div><hr><div class="row"><div class="col-md-1 viewers"><h4>392</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/global-equities-time-breather/"><h4>Global Equities: Time for a breather?</h4></a><div class="text-muted">Dow 20453 / World 1843/ BRIC 270 / Nifty 9150 / Russell 2k 1345

The global...</div></div></div><hr><div class="row"><div class="col-md-1 viewers"><h4>691</h4><span class="text-muted">views</span></div><div class="col-md-11"><a href="http://colourofmoney.kshitij.com/got-kshitij-com-advantage/"><h4>Have you got the Kshitij.com Advantage?</h4></a><div class="text-muted">Highlights of Kshitij Forecasts: 2016
Kshitij has been making long term forecast for almost the last...</div></div></div></div><div class="clearfix"></div>

</div></div></div><p></p>
				<!-- .entry-content -->
@stop
@section('sidebar')

@stop